keys:
  - &nixtop age1km3dl0mjq35ddhevlhfzelz62wkp4l2ehcg7xl4zlx5ufpk09drsvd2ds0
  - &desktop age1pmm38z4v2y9cy7gnzwt5gvztazmu4k44whwg9jwhtlfdyj0fj4psetr6gt
  - &hpl-macmini age1w3zwf6yp43fksd5crhku7w74t4s9fzlh7whtlppzh5r60jy7yy8qg0wenw
  - &hpl-tower age1ya8c4usuysj60ehy37cy893ywglglm9g8p3ay9ah0wyx34grcveszt68lk

creation_rules:
  - path_regex: secrets/[^/]+\.ya?ml$
    key_groups:
      - age:
          - *nixtop
          - *desktop
          - *hpl-macmini
          - *hpl-tower
  - path_regex: secrets/[^/]+\.json$
    key_groups:
      - age:
          - *nixtop
          - *desktop
          - *hpl-macmini
          - *hpl-tower
