# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = [
      "amdgpu.noretry=0"
      "amdgpu.vm_size=4096"
      "radeon.dpm=1"
      "radeon.audio=1"
    ];
    extraModulePackages = [ ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5385-6EAB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/791af638-2646-4a82-8ad7-731299e4aa3c";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8adbb988-258a-4840-a864-dfd456ea5002";
      fsType = "ext4";
    };

  fileSystems."/250GB-SATA" =
    { device = "/dev/disk/by-uuid/739d66ea-1708-4b87-8e4e-ec52f132b911";
      fsType = "ext4";
    };


  swapDevices = [ {
    device = "/swapfile";
    size = 24*1024; # size in MB
  } ];


  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
