# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "firewire_ohci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3f57b99e-a05c-4ffc-a1a1-2fc1bdf77aa5";
      fsType = "ext4";
    };

  fileSystems."/backup" =
    { device = "/dev/disk/by-uuid/bc41718b-0902-4860-9225-4ddd279d3fcb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1BED-50ED";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/storage/disk2" =
    { device = "/dev/disk/by-uuid/37699ad3-4d2d-4dc6-a53b-1f61694e5865";
      fsType = "ext4";
    };

  fileSystems."/storage/disk1" =
    { device = "/dev/disk/by-uuid/855ffaa0-b62f-4b5b-a325-718102ab9426";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
