HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh/zsh_history
setopt HIST_IGNORE_DUPS      
setopt HIST_IGNORE_SPACE     
setopt SHARE_HISTORY         
setopt HIST_VERIFY           
setopt AUTO_CD               
setopt CORRECT               
setopt MENU_COMPLETE         
setopt AUTO_PUSHD            
setopt PUSHD_IGNORE_DUPS     

autoload -Uz compinit
compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

bindkey -e

if [[ -d "$HOME/.oh-my-zsh/plugins/git" ]]; then
    source "$HOME/.oh-my-zsh/plugins/git/git.plugin.zsh" 2>/dev/null || true
fi

alias wc3='wine Games/wc3/drive_c/Program\ Files/Warcraft\ 3/Warcraft\ III.exe'
alias twow='cd ~/Games/twmoa_1180 && wine explorer /desktop=TurtleWoW,1920x1080 WoW.exe'
alias ll='ls -lah'
alias tm='tmux-default'
alias screenshot='grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png'
alias screenshot-clip='grim -g "$(slurp)" - | wl-copy'
alias kde-start='dbus-run-session startplasma-wayland'
alias kde-stop='qdbus org.kde.Shutdown /Shutdown org.kde.Shutdown.logout'

wpaste() {
    local delay=${1:-5}
    nix shell nixpkgs#xdotool -c sh -c '
        echo "Focus the target window, typing in '"$delay"' seconds..."
        sleep '"$delay"'
        xdotool type "$(wl-paste)"
        echo "Done - clipboard typed."
    '
}

reload_zsh() {
    local repo_zshrc="$NIX_CONFIG_DIR/modules/dotfiles/zsh/zshrc"
    if [[ -f "$repo_zshrc" ]]; then
        source "$repo_zshrc"
        echo "zshrc reloaded from repo"
    else
        echo "Error: zshrc not found at $repo_zshrc"
    fi
}
alias zreload="reload_zsh"
